### ISSUE TITLE
fold no longer works when you set the g:erlangFoldSplitFunction variable

### ISSUE THREAD

**Issue by zaphar** [oscarh/vimerl#1]
Something about the code to split function heads does not work correctly. I haven't been able to trace the problem myself. but it is definitely in those if blocks because it works fine when you don't set the variable.

**Comment by oscarh** [comment]
Actually, most of the folding code is very broken :( I will try to take a look at it, but it should probably be re-written.

**Comment by zaphar** [comment]
ahhh ok :-) That explains it. Wish I had time to tackle a patch for you but at the moment I far too busy.

**Comment by oscarh** [comment]
The folding has been refactored quite a bit in the kTT branch, please let me know if this works for you.

Enabling and disabling folding is done by vim builtin control for this though.

/Oscar
