### ISSUE TITLE
Compiler script (show_msg) fails after disabling the checking on enterting buffer

### ISSUE THREAD

**Issue by oscarh** [oscarh/vimerl#13]
In the kTT branch, a commit was cherry-picked to avoid compiling the file every time the buffer is entered since this is slow. However, this causes the script to fail, since some buffer variables aren't always initialized...

I've temporary solved this by wrapping the body of show_msg in if exists('b:error_list') but I don't feel this is the right approach...

**Comment by jimenezrick** [comment]
It was fixed here https://github.com/jimenezrick/vimerl/commit/47d27dc9990932c500b1fc3b7cbd7e4f84e0ded8 with a simplistic approach.

**Comment by oscarh** [comment]
Thanks, I'll pick this commit instead then :)

**Comment by oscarh** [comment]
Done.
