### ISSUE TITLE
Autocompletion with pathogen doesn't work

### ISSUE THREAD

**Issue by MasseR** [oscarh/vimerl#14]
When using pathogen, it's recommended to clone the submodule into ~/.vim/bundle/project. The autocompletion has set the default path for completion as "~/.vim/autoload/erlang_completion.vim", which doesn't exist when cloned as submodule into bundle/.

If you can get the current script path from vimL, you could use the relative path from the script.

> " Pseudo
> dirname($script)/erlang_completion.erl

**Comment by oscarh** [comment]
Hi!

It would be really nice if you could supply a patch for this. I haven't used pathogen, so I'd have to set that up to try and fix it.

/Oscar

**Comment by jimenezrick** [comment]
Fixed here: https://github.com/jimenezrick/vimerl/commit/e9b3b078aa77814920228cd3c65f5ab1ebe2399b

**Comment by MasseR** [comment]
@jimenezrick That's a manual solution which would be ok too, but I'd assume that for backwards compatability, automatic finding would be better. I have a couple of hours at my disposal, so I'll take a crack at it.

**Comment by MasseR** [comment]
Commit c2ce820 works for me.  As far as I understand it checks the relative path to the script, strips off the filename path and appends the erl file.

**Comment by MasseR** [comment]
On another note. What is the github etiquette with this. Should I also file a pull request?

**Comment by oscarh** [comment]
I guess you could, but I can also just merge it I think :)

**Comment by oscarh** [comment]
Pushed to my master branch.
