### ISSUE TITLE
Vim(compiler):E666: compiler not supported: erlang

### ISSUE THREAD

**Issue by foxbunny** [oscarh/vimerl#2]
I get this when I open an erlang file. Afterwards, it works ok, but I've never even tried to compile an .erl file from Vim, so I wouldn't know if this is a big problem.

**Comment by oscarh** [comment]
Which version of Vim?

**Comment by foxbunny** [comment]
Sorry, forgot to mention.

Vim 6.2 under Linux.

**Comment by foxbunny** [comment]
Sorry, I mistyped that: 7.2 under Linux.

**Comment by oscarh** [comment]
I removed the compiler script... It will be added again, in a new version soonish. I'm not sure about these compiler scripts to be honest, but if ppl want them, who am I to complain :)
